name: Add-on Validations

on:
  push:
    branches: [ master, Leia ]

  pull_request:
    branches: [ master, Leia ]

jobs:

  addon-validations:
    if: github.repository == 'gade01/Rapier'

    name: Add-on Validations
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python v3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Checkout Add-on
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install arrow
          python -m pip install requests
          python -m pip install isort
          python -m pip install pylint
          python -m pip install git+https://github.com/xbmc/addon-check.git

      - name: Staging for Leia
        run: |
          git reset
          git checkout .
          git clean -fdx
          git apply .patches/leia.patch
        working-directory: ${{ github.event.repository.name }}

      - name: Kodi Add-on Checker (Leia)
        id: kodi-addon-checker-leia
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=Leia

      - name: Staging for Matrix
        run: |
          git reset
          git checkout .
          git clean -fdx
          git apply .patches/matrix.patch
        working-directory: ${{ github.event.repository.name }}

      - name: Kodi Add-on Checker (Matrix)
        id: kodi-addon-checker-matrix
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=master

      - name: Re-staging Repository
        run: |
          git reset
          git checkout .
          git clean -fdx
        working-directory: ${{ github.event.repository.name }}

      - name: Pylint
        id: pylint
        run: |
          cp -t ${HOME} .pylintrc
          pylint resources/lib/
        working-directory: ${{ github.event.repository.name }}

      - name: isort
        id: isort
        run: |
          isort --force-single-line-imports . --diff
        working-directory: ${{ github.event.repository.name }}