name: Add-on Validations
 
on:
  push:
    branches: [ master ]
 
  pull_request:
    branches: [ master ]
 
jobs:
  addon-validations:
    if: github.repository == 'gade01/Rapier'
 
    name: Add-on Validations
    runs-on: ubuntu-latest
 
    steps:
      - name: Set up Python v3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
 
      - name: Checkout Add-on
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/xbmc/addon-check.git
 
      - name: Kodi Add-on Checker
        id: kodi-addon-checker
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=matrix