# Based on https://github.com/im85288/service.upnext/blob/master/.github/workflows/release.yml
name: Make Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.repository == 'gade01/Rapier'

    name: Make Release
    runs-on: ubuntu-latest

    steps:
      - name: Release Status
        id: release
        run: |
          version=${GITHUB_REF/refs\/tags\//}

      - name: Checkout Add-on
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          sudo apt-get install libxml2-utils xmlstarlet zip

      - name: Get Changelog
        id: changelog
        run: |
          changes=$(xmlstarlet sel -t -v '//news' -n addon.xml)
          changes="${changes//'%'/'%25'}"
          changes="${changes//$'\n'/'%0A'}"
          changes="${changes//$'[CR]'/'%0A'}"
          changes="${changes//$'\r'/'%0D'}"
          changes="${changes//$'[B]'/'**'}"
          changes="${changes//$'[/B]'/'**'}"
          changes="${changes//$'[I]'/'%0A%0A*'}"
          changes="${changes//$'[/I]'/'*'}"
          echo ::set-output name=changes::$changes
        working-directory: ${{ github.event.repository.name }}

      - name: Remove Unwanted Files
        run: |
          mv .git ..
          mv .github ..
        working-directory: ${{ github.event.repository.name }}

      - name: Create Zip (Matrix)
        id: zip-matrix
        run: |
          version=$(xmlstarlet sel -t -v 'string(/addon/@version)' addon.xml)
          id=$(xmlstarlet sel -t -v 'string(/addon/@id)' addon.xml)
          filename=${id}-${version}.zip
          cd ..
          zip -r $filename ${{ github.event.repository.name }}
          echo ::set-output name=filename::$filename
        working-directory: ${{ github.event.repository.name }}

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Matrix ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: ${{ steps.release.outputs.pre-release }}

      - name: Upload Zip (Matrix)
        id: upload-matrix
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_name: ${{ steps.zip-matrix.outputs.filename }}
          asset_path: ${{ steps.zip-matrix.outputs.filename }}
          asset_content_type: application/zip